language: python
install:
    - pip install pipenv
    - pipenv install
    - npm install
script:
    - pipenv check
    - pipenv run flake8 life_track --exclude=migrations
    - pipenv run flake8 timeline --exclude=migrations
    - pipenv run python manage.py test
    - npm run build
    - npm run test
