# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 2, 7, 1, 356470, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 2, 7, 16, 204556, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
