# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20190107_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
